### Generated by rprotoc. DO NOT EDIT!
### <proto file: doozerd/server/msg.proto>
# package server;
#
# // see doc/proto.md
# message Request {
#   optional int32 tag = 1;
#
#   enum Verb {
#       GET      = 1;
#       SET      = 2;
#       DEL      = 3;
#       REV      = 5;
#       WAIT     = 6;
#       NOP      = 7;
#       WALK     = 9;
#       GETDIR   = 14;
#       STAT     = 16;
#       ACCESS   = 99;
#   }
#   optional Verb verb = 2;
#
#   optional string path = 4;
#   optional bytes value = 5;
#   optional int32 other_tag = 6;
#
#   optional int32 offset = 7;
#
#   optional int64 rev = 9;
# }
#
# // see doc/proto.md
# message Response {
#   optional int32 tag = 1;
#   optional int32 flags = 2;
#
#   optional int64 rev = 3;
#   optional string path = 5;
#   optional bytes value = 6;
#   optional int32 len = 8;
#
#   enum Err {
#     // don't use value 0
#     OTHER        = 127;
#     TAG_IN_USE   = 1;
#     UNKNOWN_VERB = 2;
#     READONLY     = 3;
#     TOO_LATE     = 4;
#     REV_MISMATCH = 5;
#     BAD_PATH     = 6;
#     MISSING_ARG  = 7;
#     RANGE        = 8;
#     NOTDIR       = 20;
#     ISDIR        = 21;
#     NOENT        = 22;
#   }
#   optional Err err_code = 100;
#   optional string err_detail = 101;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Skynet
  module Doozer
    class Request < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :tag, 1
      class Verb < ::Protobuf::Enum
        defined_in __FILE__
        GET = value(:GET, 1)
        SET = value(:SET, 2)
        DEL = value(:DEL, 3)
        REV = value(:REV, 5)
        WAIT = value(:WAIT, 6)
        NOP = value(:NOP, 7)
        WALK = value(:WALK, 9)
        GETDIR = value(:GETDIR, 14)
        STAT = value(:STAT, 16)
        ACCESS = value(:ACCESS, 99)
      end
      optional :Verb, :verb, 2
      optional :string, :path, 4
      optional :bytes, :value, 5
      optional :int32, :other_tag, 6
      optional :int32, :offset, 7
      optional :int64, :rev, 9
    end
    class Response < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :tag, 1
      optional :int32, :flags, 2
      optional :int64, :rev, 3
      optional :string, :path, 5
      optional :bytes, :value, 6
      optional :int32, :len, 8
      class Err < ::Protobuf::Enum
        defined_in __FILE__
        OTHER = value(:OTHER, 127)
        TAG_IN_USE = value(:TAG_IN_USE, 1)
        UNKNOWN_VERB = value(:UNKNOWN_VERB, 2)
        READONLY = value(:READONLY, 3)
        TOO_LATE = value(:TOO_LATE, 4)
        REV_MISMATCH = value(:REV_MISMATCH, 5)
        BAD_PATH = value(:BAD_PATH, 6)
        MISSING_ARG = value(:MISSING_ARG, 7)
        RANGE = value(:RANGE, 8)
        NOTDIR = value(:NOTDIR, 20)
        ISDIR = value(:ISDIR, 21)
        NOENT = value(:NOENT, 22)
      end
      optional :Err, :err_code, 100
      optional :string, :err_detail, 101
    end
  end
end